site_name: 'Утильсбор за машины, произведенные в Кахазстане'
docs_dir: docs
repo_url: https://github.com/zachestniyutil/avto_iz_KZ
theme:
  name: material
  custom_dir: overrides
  language: 'ru'
  palette:
    primary: black
    accent: yellow
  # custom_dir: swagger-iu/
plugins:
  - search:
      indexing: 'full'
      lang:
        - en
        - ru
      min_search_length: 3
      prebuild_index: false
      separator: "[\\s\\-]+"

nav:
- Главное: 
  - "Описание проблемы": index.md
  - "Часто задаваемые вопросы": faq.md
  - "Документы": docs.md

- Судебная практика:
  - "Вынесенные решения" : protocols.md